version: 2
jobs:
  build:
    #working_directory: /go/src/github.com/jszwedko/go-circleci
    environment:
      TEST_RESULTS: /tmp/test-results
    docker:
    - image: circleci/golang:latest
    steps:
    - checkout
    - run: go vet ./...
    - run: go test ./...
